### ISSUE TITLE
Error deserializing routing file in CalculateMatrix sample

### ISSUE THREAD

**Issue by gjdownes** [OsmSharp/samples#2]
I get the following error running the CalculateMatrix sample:
"Cannot deserialize the given stream, version unsupported or content unrecognized!"

The offending line is:
var graph = serializer.Deserialize (stream, out metaTags, false);

I've copied the sample .routing file as an embedded resource in my VS project. 

Currently using OsmSharp 4.2.0.723 

Thanks

**Comment by gjdownes** [comment]
The sample files contained older headers, that was causing the issue. Creating a file with the latest odp tool fixed the issue.

**Comment by pajaro5** [comment]
@gjdownes does the new file solved the error?  I created a new file usign
`odp --read-pbf ecuador-latest.osm.pbf --create-routerdb vehicles=car --contract car --write-routerdb kempen-big.osm.pbf.contracted.flat.routing`

But I'm still getting the same error.
